### ISSUE TITLE
** Bug ** Push Messages Delivered inconsistantly

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-iOS-SDK#401]
## GOAL ## 
Show notifications and do sync call while application is closed. 

## Expectation ##
App syncs in the background and shows notification to user. 

## Result ##
Push messages are inconsistent from iOS to iOS device Vs Android to iOS Device. 

## Code ##

Push Message Received when sending a message from an iOS device to iOS Device
```objective-c

{
    "AL_KEY":"APPLOZIC_01";
    "AL_VALUE":"{"id":"15f34707130494cd8bd43122b702c3e32","type":"APPLOZIC_01","message":"3227864.qa","notifyUser":true,"totalUnreadCount":5,"sendAlert":false,"messageMetaData":{"NO_ALERT":"true"}}";
    aps =     {
        badge = 5;
        "content-available" = 1;
	}
}

```

Push Message Received when sending a message from an Android device to iOS Device
```objective-c
{
    "AL_KEY" = "APPLOZIC_01";
    "AL_VALUE" = "{"id":"3619ea94fb9713a17f0bc8d71256f7d7c","type":"APPLOZIC_01","message":"3227960.qa","notifyUser":true,"totalUnreadCount":6,"sendAlert":true,"messageMetaData":{}}";
    aps =     {
        alert = "T T: Fdgh";
        badge = 6;
        "content-available" = 1;
        sound = default;
    }
}

```

According to Apple Docs - For Silent Notifications (background sync), content-available should be set, without Alert, Badge or Sound, so the background sync can occur. So Ideally two pushes should be sent. One push with only content available, and another with message the alert, badge and sound flags.

I see iOS still tries to do the background sync call even if all 4 flags exist in one push (no real issue then), but for iOS to iOS, the alert flag is still missing. So the badge updates, the background sync gets called, but there is no "alert" flag which displays the notification in notification center. 

This all happens while the applicaiton is closed.

**Comment by mukeshthawani** [comment]
Can you share any use case where this is causing any problem?

**Comment by adamsrosco** [comment]
Hi,

Use Case: When the application is completely closed, a user should be notified of the message sent to them. Currently no notification is being shown  (even when the push message arrives) when the push message arrives. only the application badge updates.

**Comment by mukeshthawani** [comment]
We will look into it. Please share logs at support@applozic.com

**Comment by adamsrosco** [comment]
Emailed. Thanks.

**Comment by devrajblr** [comment]
Hello @adamsrosco ,
I have read the issue and checked both the push messages.

**iOS device to iOS device:**
I can see the NO_ALERT flag is true in the message metadata.
`"messageMetaData":{"NO_ALERT":"true"}`
That means no any notification will be displayed in the device for this message, but the badge count will be displayed or updated.
That's why you are not getting notification. If the message metadata is blank or NO_ALERT is set to false, then you should get the notification.

**Android device to iOS device:**
I can see the message metadata is blank for this message.
`"messageMetaData":{}`
So, it will behave as default. It will send the notification and update the badge count.

Message metadata is configured in the send message API.
If you set badge count as false in message metadata, then badge count also will not be updated.
`"messageMetaData":{"BADGE_COUNT":"false"}`

Regards,
Devraj K.
